services:
  openvpn:
    build:
      context: ./openvpn
      dockerfile: Dockerfile
    image: openvpn:v2
    pull_policy: never
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ovpn-data:/etc/openvpn
    networks:
      vpn_network:
        ipv4_address: 172.20.0.254
    restart: always
    profiles:
      - openvpn

  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "127.0.0.1:53:53/udp"
    networks:
      vpn_network:
        ipv4_address: 172.20.0.253
    cap_add:
      - NET_ADMIN
    profiles:
      - openvpn

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html:/var/www/html
      - ${SSL_CERTIFICATE_FILE}:${SSL_CERTIFICATE_FILE}
      - ${SSL_CERTIFICATE_KEY_FILE}:${SSL_CERTIFICATE_KEY_FILE}
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      vpn_network:
        ipv4_address: 172.20.0.2
    restart: always
    profiles:
      - web
    environment:
      - SERVER_ADMIN=${SERVER_ADMIN}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - WIKI_DOMAIN=${WIKI_DOMAIN}
      - PLANKA_DOMAIN=${PLANKA_DOMAIN}
      - GAIA_PLANKA_DOMAIN=${GAIA_PLANKA_DOMAIN}
      - GAIA_WIKI_DOMAIN=${GAIA_WIKI_DOMAIN}
      - GITEA_DOMAIN=${GITEA_DOMAIN}
      - SSL_CERTIFICATE_FILE=${SSL_CERTIFICATE_FILE}
      - SSL_CERTIFICATE_KEY_FILE=${SSL_CERTIFICATE_KEY_FILE}

  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      vpn_network:
        ipv4_address: 172.20.0.3
    restart: always
    profiles:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      vpn_network:
        ipv4_address: 172.20.0.4
    restart: always
    profiles:
      - web

  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    volumes:
      - planka-data:/app
      - planka-user-avatars:/app/public/user-avatars
      - planka-project-background-images:/app/public/project-background-images
      - planka-attachments:/app/private/attachments
    ports:
      - "127.0.0.1:1337:1337"
    environment:
      - BASE_URL=${PLANKA_BASE_URL}
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=${PLANKA_SECRET_KEY}
      - DEFAULT_ADMIN_EMAIL=${PLANKA_DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${PLANKA_DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_NAME=${PLANKA_DEFAULT_ADMIN_NAME}
      - DEFAULT_ADMIN_USERNAME=${PLANKA_DEFAULT_ADMIN_USERNAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      vpn_network:
        ipv4_address: 172.20.0.5
    profiles:
      - pw

  wiki:
    image: ghcr.io/requarks/wiki:latest
    depends_on:
      - postgres
    environment:
      ADMIN_EMAIL: ${WIKI_ADMIN_EMAIL}
      ADMIN_PASS: ${WIKI_ADMIN_PASS}
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - wiki-data:/wiki
    networks:
      vpn_network:
        ipv4_address: 172.20.0.6
    profiles:
      - pw

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      vpn_network:
        ipv4_address: 172.20.0.7
    profiles:
      - pw

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - gitea-data:/data
    ports:
      - "3002:3000"
      - "2222:22"
    depends_on:
      - postgres
    networks:
      vpn_network:
        ipv4_address: 172.20.0.8
    restart: always
    profiles:
      - pw

  gaia-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${GAIA_POSTGRES_DB}
      POSTGRES_PASSWORD: ${GAIA_POSTGRES_PASSWORD}
      POSTGRES_USER: ${GAIA_POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - gaia-postgres_data:/var/lib/postgresql/data
    networks:
      vpn_network:
        ipv4_address: 172.20.1.3
    profiles:
      - gaia
      - gaia-bdd

  gaia-planka:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    volumes:
      - gaia-planka-data:/app
      - gaia-planka-user-avatars:/app/public/user-avatars
      - gaia-planka-project-background-images:/app/public/project-background-images
      - gaia-planka-attachments:/app/private/attachments
    ports:
      - "127.0.0.1:3002:1337"
    environment:
      - BASE_URL=${GAIA_PLANKA_BASE_URL}
      - DATABASE_URL=postgresql://postgres@gaia-postgres/planka
      - SECRET_KEY=${GAIA_PLANKA_SECRET_KEY}
      - DEFAULT_ADMIN_EMAIL=${GAIA_PLANKA_DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${GAIA_PLANKA_DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_NAME=${GAIA_PLANKA_DEFAULT_ADMIN_NAME}
      - DEFAULT_ADMIN_USERNAME=${GAIA_PLANKA_DEFAULT_ADMIN_USERNAME}
    depends_on:
      gaia-postgres:
        condition: service_healthy
    networks:
      vpn_network:
        ipv4_address: 172.20.1.1
    profiles:
      - gaia

  gaia-wiki:
    image: ghcr.io/requarks/wiki:latest
    depends_on:
      - gaia-postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: gaia-postgres
      DB_PORT: 5432
      DB_USER: ${GAIA_POSTGRES_USER}
      DB_PASS: ${GAIA_POSTGRES_PASSWORD}
      DB_NAME: ${GAIA_POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - gaia-wiki-data:/wiki
    networks:
      vpn_network:
        ipv4_address: 172.20.1.2
    profiles:
      - gaia

volumes:
  mysql_data:
    name: mysql-data
  ovpn-data:
    name: ovpn-data
  ovpn-bin:
    name: ovpn-bin
  planka-data:
    name: planka-data
  planka-user-avatars:
    name: planka-user-avatars
  planka-project-background-images:
    name: planka-project-background-images
  planka-attachments:
    name: planka-attachments
  wiki-data:
    name: wiki-data
  postgres_data:
    name: postgres_data
  mailserver-data:
    name: mailserver-data
  mailserver-certs:
    name: mailserver-certs
  gaia-planka-data:
    name: gaia-planka-data
  gaia-planka-user-avatars:
    name: gaia-planka-user-avatars
  gaia-planka-project-background-images:
    name: gaia-planka-project-background-images
  gaia-planka-attachments:  
    name: gaia-planka-attachments
  gaia-wiki-data: 
    name: gaia-wiki-data
  gaia-postgres_data:
    name: gaia-postgres_data
  gitea-data:
    name: gitea-data

networks:
  vpn_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
#    driver: bridge
#    external: false
