services:
  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
      - "444:444"
      - "445:445"
    volumes:
      - ./data/apache:/var/www/html
      - ${SSL_CERTIFICATE_FILE}:${SSL_CERTIFICATE_FILE}
      - ${SSL_CERTIFICATE_KEY_FILE}:${SSL_CERTIFICATE_KEY_FILE}
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      vpn_network:
        ipv4_address: 172.10.0.2
    restart: always
    environment:
      - SERVER_ADMIN=${SERVER_ADMIN}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - WIKI_DOMAIN=${WIKI_DOMAIN}
      - PLANKA_DOMAIN=${PLANKA_DOMAIN}
      - SSL_CERTIFICATE_FILE=${SSL_CERTIFICATE_FILE}
      - SSL_CERTIFICATE_KEY_FILE=${SSL_CERTIFICATE_KEY_FILE}

  planka:
    image: ghcr.io/plankanban/planka:1.25.0
    restart: on-failure
    container_name: planka
    volumes:
      - planka_data:/app
    ports:
      - "127.0.0.1:1337:1337"
    environment:
      - BASE_URL=${PLANKA_BASE_URL}
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=${PLANKA_SECRET_KEY}
      - DEFAULT_ADMIN_EMAIL=${PLANKA_DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${PLANKA_DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_NAME=${PLANKA_DEFAULT_ADMIN_NAME}
      - DEFAULT_ADMIN_USERNAME=${PLANKA_DEFAULT_ADMIN_USERNAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      vpn_network:
        ipv4_address: 172.10.0.3

  wiki:
    image: ghcr.io/requarks/wiki:latest
    container_name: wiki
    depends_on:
      - postgres
    environment:
      ADMIN_EMAIL: ${WIKI_ADMIN_EMAIL}
      ADMIN_PASS: ${WIKI_ADMIN_PASS}
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - wiki_data:/wiki
    networks:
      vpn_network:
        ipv4_address: 172.10.0.4

  postgres:
    #image: postgres:15-alpine
    container_name: postgres
    build: 
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s 
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./kronos/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      vpn_network:
        ipv4_address: 172.10.0.5
  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SERVER_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PG_SERVER_NAME: ${PG_SERVER_NAME}
      PG_SERVER_HOST: ${PG_SERVER_HOST}
      PG_SERVER_PORT: ${PG_SERVER_PORT}
      PG_SERVER_USER: ${PG_SERVER_USER}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    #  - ./docker/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh:ro # useless for now
    ports:
      - '8080:80'
    depends_on:
      - postgres
    networks:
      vpn_network:
        ipv4_address: 172.10.0.6
      
  kronos:
    build:
      context: .
      dockerfile: docker/python/Dockerfile.dev
    container_name: kronos
    working_dir: /app/src
    volumes:
      - ./kronos/src:/app/src
      - ./.env:/app/src/.env
      - ./kronos/requirements.txt:/app/requirements.txt
      - ./kronos/models:/app/models
      - ./kronos/data:/app/data
      - ./kronos/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    command: tail -f /dev/null # Keep the container running for development
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


volumes:
  planka_data:
    name: planka_data
  wiki_data:
    name: wiki_data
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data

networks:
  vpn_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
#    driver: bridge
#    external: false
